(let ((dir "/Users/shitikanth/Documents")))
(let ((dir "/Users/shitikanth/Documents")))
(let ((dir "/Users/shitikanth/Documents")))
(let ((dir "/Users/shitikanth/Documents"))
	 (while dir
	   (message "%s" dir)))
(with-current-buffer "*compilation*")
(with-current-buffer "*compilation*" 
	 )
(with-current-buffer "*compilation*" 
	 )
(with-current-buffer "*compilation*" 
	 )
(with-current-buffer "*compilation*" 
	 )
(with-current-buffer "*compilation*" 
	 
	 )
(with-current-buffer "*compilation*" 
	 
	 )
(with-current-buffer "*compilation*" 


	 
	 )
(with-current-buffer "*compilation*" 
	 (point)
	 )
(with-current-buffer "*compilation*" 
	 (point)
	 )
(with-current-buffer "*compilation*" 
	 (point)
	 )
(with-current-buffer "*compilation*" 
	 (thing-at-point 'word)
	 )
(with-current-buffer "*compilation*" 
	 (thing-at-point 'symbol)
	 )
(with-current-buffer "*compilation*" 
	 (thing-at-point 'filename)
	 )
whitespace-style
(setq whitespace-style (cdr whitespace-style))
(setq whitespace-style '(trailing space-before-tab indentation empty space-after-tab))
(setq whitespace-style '(face lines-tail))
(setq whitespace-style '(trailing lines tab-mark))
(setq whitespace-style '(face trailing lines tab-mark))
(setq whitespace-style '(face tabs empty trailing lines-tail))
(setq whitespace-style '(trailing lines tab-mark))
(setq whitespace-style '(face trailing lines tab-mark))
(setq whitespace-style '(face trailing tab-mark))
(setq whitespace-style '(face ; show ...
                         tabs tab-mark ; the tabulations,
                         lines-tail ; lines too long (> fill-column characters),
                         trailing)) ; and trailing spaces
(setq whitespace-style '(trailing space-before-tab indentation empty space-after-tab))
(setq whitespace-style '(face trailing space-before-tab indentation empty space-after-tab))
(setq whitespace-style '(face trailing space-before-tab empty space-after-tab))
(setq whitespace-style '(face indentation trailing space-before-tab empty space-after-tab))
(setq whitespace-style '(face indentation tabs trailing space-before-tab empty space-after-tab))
(setq whitespace-style '(face indentation tab-mark trailing space-before-tab empty space-after-tab))
(setq whitespace-style '(face tab-mark trailing space-before-tab empty space-after-tab))
hippie-expand-try-functions-list
(setq whitespace-style '(face tab-mark trailing))
