#!/bin/sh
# My aliases
alias screen='screen -s /bin/bash'
alias wee='weechat-curses'
alias cal='cal -3'
alias today='date "+%A, %B %-d, %Y"'
alias sudo='sudo -E'
alias reboot="sudo shutdown -r now"
alias off="sudo shutdown -h now"
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'
alias grep='grep --color=auto'
alias ls='ls --color=auto'
alias less='less -r'
alias ll='ls -l'
alias la='ls -A'
alias lla='ls -lA'
alias lS='ls -Ss'
alias las='ls -aSs'
alias lls='ls -lS'
alias llas='ls -lAS'
alias l='ll'
alias lals='llas'
alias lc='ls --color=none'
alias c='clear'
alias brc='vim ~/.bashrc'
alias reload='. ~/.bashrc'
alias back='cd "$OLDPWD"'
alias cu='cd ..'
alias r='reload'
alias b='back'
alias vimr='vim --remote-silent'
alias vimrt='vim --remote-tab-silent'
alias ec='emacsclient -n -c'
alias e='TERM=xterm emacsclient --nw -c'
alias ecc='ec -s clojure'
alias c++11='clang++ -std=c++11'
alias c++14='clang++ -std=c++14'
alias cpp='c++14 -g -Wall'
alias start='xdg-open'

# Git
alias gt='git --no-pager'
alias gdf='git diff'
alias gad='git add'
alias gadd='git add'
alias gca='git commit -a'
alias gcm='git commit -m'
alias gst='gt status -s'
alias gpl='git pull'
alias glog='git log'
alias gbr='git branch'
alias gco='git checkout'

# Mis-spelled commands
alias gvb='gdb'
alias gbim='gvim'
alias bim='vim'
alias cim='vim'
alias gvbim='gvim'
alias gbvim='gvim'
alias les='less'
alias relaod='reload'
alias yourt='yaourt'
alias mkdor='mkdir'
alias :ghci='ghci'
alias cd..='cd ..'
alias udo='sudo'
#PS1='[\u:\h \W]\$ '

if [ `uname -s` = Darwin ]
then source ~/.aliases.darwin
fi

if [ -n "$ZSH_VERSION" ]
then source ~/.aliases.zsh
fi

alias uwdev='ssh uwlinux -t dev-tmux'
