#!/bin/bash
#
# ~/.bashrc
#

# If not running interactively, don't do anything
[ -z "$PS1" ] && return

PS1='\h:\w\$ '
OS='uname -s'

shopt -s checkwinsize
shopt -s extglob
shopt -s globstar
shopt -s histappend
set -o ignoreeof

# My aliases
source ~/.aliases

# Useful functions
source ~/.bashrc.functions

export EDITOR=vim
export TERM=xterm-256color

export GTEST=/usr/local/gtest
alias gtest="g++ -g -I${GTEST}/include -L${GTEST} -lgtest -lpthread"

#
# Load SSH environment, starting a new SSH agent if needed
SSH_ENV="$HOME/.ssh/environment"
function start_agent {
    echo "Initialising new SSH agent..."
    ssh-agent | sed 's/^echo/#echo/' > "${SSH_ENV}"
    echo succeeded
    chmod 600 "${SSH_ENV}"
    . "${SSH_ENV}" > /dev/null
    ssh-add;
}
if [ -f "${SSH_ENV}" ]; then
    . "${SSH_ENV}" > /dev/null
    ps -ef | grep ${SSH_AGENT_PID} | grep ssh-agent$ > /dev/null || {
        start_agent;
    }
else
    start_agent;
fi

[ -f ~/.fzf.bash ] && source ~/.fzf.bash
