#!/bin/sh
pathmunge () {
    if [ ! -d "$1" ]; then
	return
    fi

    case ":${PATH}:" in
        *:"$1":*)
            ;;
        *)
            if [ "$2" = "after" ] ; then
                PATH=$PATH:$1
            else
                PATH=$1:$PATH
            fi
    esac
}

pathmunge "$HOME/.bin"
pathmunge "$HOME/.local/bin"
pathmunge "$HOME/.gem/ruby/2.0.0/bin"
pathmunge "$HOME/.cargo/bin"
pathmunge "$HOME/.local/node/bin"

export GOPATH="$HOME/.go"
pathmunge "$GOPATH/bin"

export MANPATH="$HOME/.local/share/man:$MANPATH"
export LD_LIBRARY_PATH="$HOME/.local/lib"
