#!/bin/sh

export PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin
export PATH=/usr/local/sbin:$PATH
export PATH="$HOME/.bin:$HOME/.local/bin:$PATH"

if [ -d "$HOME/.gem/ruby/2.0.0/bin" ]; then
    export PATH="$HOME/.gem/ruby/2.0.0/bin:$PATH"
fi

if [ -d "$HOME/.cargo/bin" ]; then
    export PATH="$HOME/.cargo/bin:$PATH"
fi

if [ -d "$HOME/.local/node/bin" ]; then
    export PATH="$HOME/.local/node/bin:$PATH"
fi

export GOPATH="$HOME/.go"
if [ -d "$GOPATH" ]; then
    export PATH="$GOPATH/bin:$PATH"
fi

export MANPATH="$HOME/.local/share/man:$MANPATH"
export LD_LIBRARY_PATH="$HOME/.local/lib"
