#!/bin/sh
# Usage: ci/lint-elisp [--fix] [FILE...]
# With no FILE, checks every tracked .el file under _emacs.d.old.
set -e
cd "$(git rev-parse --show-toplevel)"
fix=
if [ "$1" = --fix ]; then
  fix=--fix
  shift
fi
[ $# -gt 0 ] || set -- $(git ls-files '_emacs.d.old/*.el')
exec "${EMACS:-emacs}" --batch -Q -l ci/lint-elisp.el -f lint-elisp-batch $fix "$@"
